### ISSUE TITLE
Not found bakeoff library in lib directory

### ISSUE THREAD

**Issue by jockerxlj** [dotnet54/TS-CHIEF#1]
I clone, import lib and then run the MainApplication.java. Eclipse shows an error about finding bakeoff library. I cannot find the bakeoff from google. And according to the .classpath, it seems that bakeoff is an another project place in / directory.
Is it necessary to import the bakeoff? if so, how can I find the bakeoff?

**Comment by dotnet54** [comment]
Hi, its not necessary to run ts-chief algorithm. you can safely remove the reference to the bakeoff project. ~ it has been removed in the latest update.
